// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser, LocalTokenGroup} from "@lezer/lr"
import {highlight} from "./props.js"
export const parser = LRParser.deserialize({
  version: 14,
  states: ")SQ]QPOOPhOPOOOmOPO'#CbOrOPO'#CsOOQO'#Ca'#CaOwQPO'#DQQ!VQPOOOOQO'#C`'#C`P!_OpO'#C]POOO)C?O)C?OO!jOPO,58|O!rOPO,59_OOQO,59l,59lO!}QPO,59lO]QPO,59mO]QPO,59mPOOO'#DU'#DUP#YOpO,58wPOOO,58w,58wO#eOPO1G.hO#jOPO1G.hO#oOPO1G.yO#tOPO1G.yO#yOPO1G.yOOQO1G/W1G/WOOQO1G/X1G/XO$OQPO1G/XPOOO-E7S-E7SPOOO1G.c1G.cO$^OPO7+$SO$fOPO7+$SO$kOQO7+$eO$^OPO7+$eO$pOSO7+$eO$uOPO'#CfO$zOPO'#CfOOQO<<Gn<<GnO%POPO'#CqO%UOPO'#CvOOQO<<HP<<HPO%ZOPO'#C{O%`OPO,59QO%eOQO,59QO%`OPO,59]O%mOPO,59bO%rOPO,59gO%wOWO'#CiOOQO1G.l1G.lO&PO`O'#ClOOQO1G.w1G.wOOQO1G.|1G.|OOQO1G/R1G/ROOOO'#DV'#DVO&[OWO,59TOOQO,59T,59TOOOO'#DW'#DWO&dO`O'#CnO&oO`O,59WOOOO-E7T-E7TOOQO1G.o1G.oOOOO-E7U-E7UOOQO1G.r1G.r",
  stateData: "&t~O}OSQOS!OPQ~OVQOhROsTO~O!OWO~OWYO~OWZO~OVQOhROr[OsTO~Ov^Ow_O~O!P`O!Q`O!RbO~OXcOddO~OieOmfOngO~OrhOv^Ow_O~O!P`O!Q`O!RlO~OWmO~OWnO~OWoO~OWpO~OWqO~Ov^Owui{uirui~OZrO_sO~OfuO~OkvO~OpxO~O[yO~O[zO~O[{O~O[|O~O[}O~O!S!OO~Oa!QO!S!OO~Ol!SO~Oq!TO~O^!UO!S!WO~O!T!XO!U!XOcbP~O^!UO!S!]O~O!T!XO!U!XOcbX~Oc!_O~O",
  goto: "#i{P|PP!P!]!cPPP!iPP!oPP!vP!yPP!|P!cPP#PPPPP#SPPPP!]!]PP#V#]#cRXPQUOQ]TQi^Rj_XVOT^_XSOT^_QtmRwpS!PyzR!R{R!PzR!Z!QRtnRwoRwqQaWRkaQ!V!OR![!VQ!Y!QR!^!Y",
  nodeNames: "⚠ BlockComment LineComment WSQL Query Clause WsClause WsNamespace Dot WsStringFieldName StringExpression StringOperator Colon StringValue StringChar RegexOperator RegexValue RegexDelim RegexContent / WsDateFieldName DateExpression DateOperator StreamClause StreamNamespace StreamIntFieldName IntExpression IntOperator IntValue StreamStringFieldName StreamBoolFieldName BoolExpression BoolOperator BoolValue RightParen LeftParen GroupQuery LogicalQuery And Or",
  maxTerm: 52,
  nodeProps: [
    ["openedBy", 34,"LeftParen"],
    ["closedBy", 35,"RightParen"]
  ],
  propSources: [highlight],
  skippedNodes: [0,1,2,40],
  repeatNodeCount: 3,
  tokenData: "5}~R![X^$wpq$|qr%Trs%Ysx%Txy%_yz%fz!O%T!O!P%m!P!Q%t!Q![&o![!]'R!]!c%T!c!d'Y!d!q%T!q!r'm!r#O%T#O#P'z#P#T%T#T#U)l#U#V%T#V#W)z#W#X+o#X#Y,x#Y#Z-Z#Z#[.g#[#]/O#]#`%T#`#a/i#a#b%T#b#c0Q#c#d1^#d#e1f#e#f%T#f#g3X#g#h3j#h#i4|#i#k%T#k#l5j#l#y%T#y#z$|#z$f%T$f$g$|$g#BY%T#BY#BZ$|#BZ$IS%T$IS$I_$|$I_$I|%T$I|$JO$|$JO$JT%T$JT$JU$|$JU$KV%T$KV$KW$|$KW&FU%T&FU&FV$|&FV;'S%T;'S;=`5w<%lO%TS$|O}St%TO^p}Sp%YO^p~%_O!S~t%fOsS^pt%mOrS^pt%tOWS^p|%{QaW^pz{&R!P!Q&WS&WO!OSS&]SQSOY&WZ;'S&W;'S;=`&i<%lO&WS&lP;=`<%l&Wt&vPlS^p!Q![&yS'OPlS!Q![&yt'YO[S^pt'_P^p!p!q'bS'eP!f!g'hS'mOvSt'rP^p!t!u'uS'zOwSp'}Xrs%T!P!Q%T#O#P%T#U#V%T#Y#Z%T#b#c%T#f#g%T#h#i%T#i#j(jp(mR!Q![(v!c!i(v#T#Z(vp(yR!Q![)S!c!i)S#T#Z)Sp)VR!Q![)`!c!i)`#T#Z)`p)cR!Q![%T!c!i%T#T#Z%Tt)qP^p#b#c)tS)wP#W#X'ht*PQ^p#c#d*V#f#g*hS*YP#b#c*]S*`P#h#i*cS*hOZSS*kP#X#Y*nS*qP#T#U*tS*wP#h#i*zS*}P#X#Y+QS+TP#W#X+WS+ZP#R#S+^S+aP#T#U+dS+gP#h#i+jS+oOdSt+tP^p#]#^+wS+zP#f#g+}S,QP#X#Y,TS,WP#V#W,ZS,^P#h#i,aS,dP#]#^,gS,jP#c#d,mS,pP#b#c,sS,xOXS!^,}P^p#e#f-Ql-ZOp`kWZSt-`Q^p#T#U-f#c#d-}S-iP#`#a-lS-oP#g#h-rS-uP#X#Y-xS-}OqSS.QP#f#g.TS.WP#a#b.ZS.^P#T#U.aS.dP#h#i,s|.lP^p#h#i.o[.vPfSkW#X#Y.yW/OOkWt/TP^p#c#d/WS/ZP#g#h/^S/aP#h#i/dS/iOmS|/nQ^p#]#^/t#h#i.oS/wP#_#`/zS/}P#X#Y*c!^0VS^p#V#W0c#X#Y-Q#`#a0i#f#g0oS0fP#c#d*VS0lP#]#^/tS0rP#X#Y0uS0xP#Z#[0{S1OP#X#Y1RS1UP#l#m1XS1^O_St1cP^p#f#g'ut1kR^p#T#U1t#c#d2Q#f#g2cS1wP#h#i1zS1}P#[#]/dS2TP#f#g2WS2ZP#h#i2^S2cOiSS2fP#c#d2iS2lP#h#i2oS2rP#c#d2uS2xP#V#W2{S3OP#c#d3RS3UP#`#a/dt3^Q^p#T#U3d#X#Y0uS3gP#k#l,st3oQ^p#c#d3u#h#i4_S3xP#i#j3{S4OP#f#g4RS4UP#V#W4XS4[P#X#Y/dS4bP#f#g4eS4hP#X#Y4kS4nP#T#U4qS4tP#a#b4wS4|OhSt5RQ^p#`#a5X#f#g5dS5[P#g#h5_S5dOnSS5gP#i#j-rt5oP^p#g#h5rS5wOVSp5zP;=`<%l%T",
  tokenizers: [2, 3, 4, 5, new LocalTokenGroup("x~RQ!P!QX#O#P^~^Oc~~aRO;'Sj;'S;=`o;=`Oj~oO!U~~tP!U~;=`<%lj~", 39, 51), new LocalTokenGroup("u~RRYZ[]^az{i~aO!Q~~fP!Q~YZ[~lP!P!Qo~tO!R~~", 36, 47)],
  topRules: {"WSQL":[0,3]},
  tokenPrec: 0
})
