[package]
name = "httpql"
authors = ["Caido Labs Inc. <dev@caido.io>"]
repository = "https://github.com/caido/httpql"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = { version = "2" }
pest_derive = { version = "2" }
